#!/bin/bash
# 推送Astro博客到GitHub的完整步骤

echo "=== 步骤 1: 设置 Git 身份 ==="
echo "请替换为你的姓名和邮箱："
echo ""
echo "  git config user.name \"你的名字\""
echo "  git config user.email \"your.email@example.com\""
echo ""

echo "=== 步骤 2: 提交代码 ==="
echo "  git add ."
echo "  git commit -m \"Initial commit: Astro travel blog\""
echo ""

echo "=== 步骤 3: 在GitHub创建仓库 ==="
echo "访问: https://github.com/new"
echo "仓库名称: travel-blog (或其他你喜欢的名字)"
echo "选择: Public 或 Private"
echo "不勾选: Initialize with README"
echo ""

echo "=== 步骤 4: 推送到GitHub ==="
echo "替换 yourusername 为你的GitHub用户名，repo-name 为仓库名："
echo ""
echo "  git remote add origin https://github.com/yourusername/repo-name.git"
echo "  git branch -M main"
echo "  git push -u origin main"
echo ""

echo "=== 步骤 5: 云服务器部署 ==="
echo "在你的云服务器上执行："
echo ""
echo "  # 安装Node.js 20+"
echo "  curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -"
echo "  sudo apt-get install -y nodejs"
echo ""
echo "  # 克隆仓库"
echo "  git clone https://github.com/yourusername/repo-name.git"
echo "  cd repo-name"
echo ""
echo "  # 安装依赖并构建"
echo "  npm install"
echo "  npm run build"
echo ""
echo "  # 配置Nginx"
echo "  # 将dist目录作为静态网站根目录"
echo "  sudo cp -r dist/* /var/www/html/"
echo ""
